language:
  - python
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgmp-dev
python:
  - "2.7"
  - "3.9-dev"
jobs:
  allow_failures:
    - python: "3.9-dev"
install:
  - "pip install -r requirements.txt"
script: 
  - "python setup.py test"
